Name:		exception
	Version:	0.4
Release:	1%{?dist}
Summary:	A debugging instrumentation and logging library for C++11

Group:		System Environment/Libraries
License:	MIT
URL:		https://github.com/CPTI/Exception
Source0:	exception.tar.bz2
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  binutils-devel
Requires:       binutils

# add --with qt option, i.e. disable qt by default
%bcond_with qt
# add --without c++11 option, i.e. enable c++11 by default
%bcond_without cxx11

%if %{with cxx11}
BuildRequires: gcc-c++ >= 4.8
%else
BuildRequires: gcc-c++
%endif

%define cmake_flags -DDUMMY=on
%if %{with qt}
BuildRequires: libqt4-devel
%if %{with cxx11}
%define cmake_flags -DSUPPORT_QT=on
%else
%define cmake_flags -DBUILD_QT=on
%endif
%endif

%description
This library provides:

- An exception hierarchy that derives from std::exception
- Runtime instrumentation to get backtraces at any time or of std::exceptions, in a catch clause
- A logging library that is integrated with the debugging instrumentation

This library is meant to improve the diagnostics of problems in Software written in C++.
There is a modular and extensible logging library that has a negligible overhead when deactivated
and has features such as colored output. The exception hierarchy contains type such as IOExcption
so that C++ project don't need to write them over and over again. It also has an easy interface to
get backtraces with debugging symbols on code generated by g++/clang++ or VisualStudio.
On a gnu compatible runtime, the runtime is instrumented to capture the throwing of any
exception derived from std::exception and make it available for printing inside a catch clause

%prep
%setup -q -n exception


%build
mkdir build
cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=/usr %{cmake_flags}
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT
cd build
make install DESTDIR=$RPM_BUILD_ROOT

#%check
#cd build/src/unit_test
#./unit_test


%clean
rm -rf $RPM_BUILD_ROOT


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig


%files
%defattr(-,root,root,-)
%doc LICENSE README.md
%{_libdir}/libexception.so
%{_libdir}/cmake/Exception/*
%{_includedir}/exception/*.h

%changelog
* Thu Jan 08 2015 Maximilien de Bayser <maxdebayser@gmail.com> 0.1
- Small fix
* Tue Dec 16 2014 Maximilien de Bayser <maxdebayser@gmail.com> 0.1
- Package first created 
